PRO/urls.py
from django.contrib import admin
from django.urls import path ,include

#static import

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),

    path('jobs/', include('job.urls',namespace='jobs')),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path ,include
from . import views

app_name='job'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),                   # jobs 
    path('fav_job/<str:slug>', views.fav_job, name='fav_job'),
    path('show_fav_job', views.show_fav_job, name='show_fav_job'),
]

job/urls.py
from django.urls import path ,include
from . import views
from . import api
from django.contrib.auth.models import User
app_name='job'

urlpatterns = [
    path('', views.job_list, name='job_list'),                   # jobs
    
    path('add',views.add_job,name= 'add_job'), # add job
    path('my_job_list',views.my_job_list,name= 'my_job_list'), 


    path('<str:slug>',views.job_detail,name='job_detail'),          # job details
    path('edit_job/<str:slug>',views.edit_job,name='edit_job'), 
    path('apply_list/<int:id>',views.apply_list,name='apply_list'), 

    ##  API

    path('api/jobs',api.job_list_api,name= 'job_list_api'),
    path('api/jobs/<int:id>',api.job_detail_api,name= 'job_detail_api'), 

    ## class 
    path('api/v2/jobs',api.JobListApi.as_view(),name= 'JobListApi'), 
    path('api/v2/jobs/create',api.JobCreate.as_view(),name= 'JobCreate'), 
    path('api/v2/jobs/<int:id>',api.JobDetail.as_view(),name= 'JobDetail'), 

]

job/models.py
from django.db import models
from django.db.models.fields import URLField
from django.utils.text import slugify
from django.contrib.auth.models import User
JOB_TYPE=(
    ('Full Time','Full Time'),
    ('Part Time','Part Time'),
)


def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "jobs/%s.%s"%(instance.id,extension)

# Create your models here.

class Category(models.Model):
    name= models.CharField(max_length=25)

    def __str__(self):
        return self.name 


class Job (models.Model):  #table

    owner = models.ForeignKey(User, verbose_name=("Job_owner"), on_delete=models.CASCADE,related_name="owner")
    title = models.CharField(max_length=100) #column 
    

    job_type = models.CharField(max_length=15,choices=JOB_TYPE)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0) 
    experience = models.IntegerField(default=1)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    address = models.CharField(max_length=100,default="unknown") 
    image = models.ImageField(upload_to=image_upload)


    slug = models.SlugField(blank=True, null=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(Job, self).save(*args,**kwargs)

    def __str__(self):
        return self.title


class Apply(models.Model):
    job = models.ForeignKey("Job", related_name=("aplly_job"), on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    email  = models.EmailField(max_length=100)
    creat_at = models.DateTimeField(auto_now=True)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=500)

    def __str__(self):
        return self.name


    

job/views.py
from django.urls import reverse
from django.shortcuts import redirect, render
from .models import Job , Apply
from django.core.paginator import Paginator
from .form import ApplyForm , JobForm , MyJobForm
from django.contrib.auth.decorators import login_required
from .filters import  JobFilter
from django.utils.text import slugify

# Create your views here.

def job_list(request):
    job_list = Job.objects.all()

    #filters
    myfilter = JobFilter(request.GET,queryset=job_list)
    job_list = myfilter.qs 

    paginator = Paginator(job_list,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'jobs':page_obj , 'myfilter':myfilter,}
    return render(request,'job/job_list.html',context)

def apply_list(request,id):
    apply_list = Apply.objects.all()
    job = Job.objects.get(id=id)
    context = {'apply_list':apply_list , 'job':job}
    return render(request,'job/apply_list.html',context)


def job_detail(request,slug):
    job_details=Job.objects.get(slug=slug)

    if request.method == 'POST':
        form = ApplyForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.job = job_details
            myform.save()
    else:
        form = ApplyForm()

    context={'job':job_details , 'form':form}
    return render(request,'job/job_details.html',context)



def my_job_list(request):
    job_list = Job.objects.all()

    context = {'myjob':job_list}
    return render(request,'job/my_job_list.html',context)

def edit_job(request , slug):
    jobs = Job.objects.get(slug = slug)
    if request.method =='POST':
        form = JobForm(request.POST , request.FILES , instance = jobs)
        if form.is_valid():
            form.save()
            return redirect('jobs:my_job_list')
    else:
        form = JobForm(instance = jobs)
    context = {'form' : form}
    return render(request,'job/edit_job.html',context)


@login_required
def add_job(request):

    if request.method == 'POST':
        form = JobForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect(reverse('jobs:job_list'))
    else:
        form = JobForm()

    return render(request,'job/add_job.html',{'form':form})

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add Now Job </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area plus_padding">
        <div class="container ">
            <div class="row ">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Post Now Job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %} 
                            {% buttons %}
                                 <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                            {% endbuttons %}     

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

job/templates/job/edit_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add Now Job </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area plus_padding">
        <div class="container ">
            <div class="row ">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit Your Job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %} 
                            {% buttons %}
                                 <button class="boxed-btn3 w-100" type="submit">Done</button>
                            {% endbuttons %}     

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

job/templates/job/job_details.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                {% comment %} <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div> {% endcomment %}
                                <div class="jobs_conetent" style="margin-left: 25px">
                                    <a href="#"><h4>{{job}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{job.address}}</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="{% url 'accounts:fav_job' job.slug%}"> <i class="ti-heart"></i> </a>
                                    {% if job.owner == request.user %}
                                    <a  style ="" href="{% url 'jobs:edit_job' job.slug%}"  class="boxed-btn3">Edit</a>
                                    <a  style ="" href="{% url 'jobs:apply_list' job.id%}"  class="boxed-btn3">Applicants</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>
   
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %} 
                            {% buttons %}
                           
                                 <button class="boxed-btn3 w-100" type="submit">Apply Now</button>

                            {% endbuttons %}     

                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published_at|date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.salary}}</span></li>
                                <li>Location: <span>{{job.address}}</span></li>
                                <li>Job Nature: <span>{{job.job_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                 
            </div>
        </div>
    </div>

{% endblock body %}

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method = "GET">
                                {% bootstrap_form myfilter.form %} 
                                <input type = "submit" value = "Sreath" class = "boxed-btn3 w-100 mt-2">
                            </form>
                        </div>


                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                {% comment %} <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                        {% for job in jobs %}

                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between" >
                                    <div class="jobs_left d-flex align-items-center">
                                        {% comment %} <div class="thumb">
                                            <img src="img/svg_icon/1.svg" alt="">
                                        </div> {% endcomment %}
                                        <div class="jobs_conetent" style="margin-left: 25px">
                                            <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{job.address}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark"  href="{% url 'accounts:fav_job' job.slug%}"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date Line: {{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                        </div>
                        {% if jobs.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                        {% if jobs.has_previous %}
                                            <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in jobs.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if jobs.has_next %}
                                            <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}

job/templates/job/my_job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Your Jobs</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">

                <div class="col-lg-9 mx-auto">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                {% comment %} <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                        {% for job in myjob %}
                            {% if job.owner == request.user %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        {% comment %} <div class="thumb">
                                            <img src="img/svg_icon/1.svg" alt="">
                                        </div> {% endcomment %}
                                        <div class="jobs_conetent" style="margin-left: 25px">
                                            <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{job.address}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="{% url 'jobs:job_list'%}"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date Line: {{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                        </div>
                        {% if jobs.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                        {% if jobs.has_previous %}
                                            <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in jobs.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if jobs.has_next %}
                                            <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}

job/templates/job/my_jobs.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Favorite Jobs</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">

                <div class="col-lg-9 mx-auto">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                {% comment %} <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                        {% for job in jobs %}

                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        {% comment %} <div class="thumb">
                                            <img src="img/svg_icon/1.svg" alt="">
                                        </div> {% endcomment %}
                                        <div class="jobs_conetent" style="margin-left: 25px">
                                            <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{job.address}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark"  href="{% url 'accounts:fav_job' job.slug%}"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date Line: {{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                        </div>
                        {% if jobs.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                        {% if jobs.has_previous %}
                                            <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in jobs.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if jobs.has_next %}
                                            <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}