PRO/urls.py
from django.contrib import admin
from django.urls import path ,include

#static import

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),

    path('jobs/', include('job.urls',namespace='jobs')),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path ,include
from . import views

app_name='job'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),                   # jobs 
    path('fav_job/<str:slug>', views.fav_job, name='fav_job'),
    path('show_fav_job', views.show_fav_job, name='show_fav_job'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from job.models import Job
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    fav_job = models.ManyToManyField(Job)

    city = models.ForeignKey('City', verbose_name=('user_city'), on_delete=models.CASCADE, blank=True, null=True)
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to='profile/')


    def __str__(self):
         return str(self.user)
## create new user ---> create new empty profile

@receiver(post_save, sender=User)
def create_user_profile(sender,instance, created ,**kwargs):
    if created:
        Profile.objects.create(user=instance)
    



class City(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2',]



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name' ,'email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','phone_number','image']

accounts/views.py
from django.contrib.auth import authenticate, login
from django.core.checks import messages
from django.shortcuts import redirect, render
from .forms import SignupForm , UserForm ,ProfileForm
from .models import Profile
from django.urls import reverse
from job.models import Job
# Create your views here.  
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data['username']
            # password = form.cleaned_data['password1']
            # user = authenticate(username='username', password='password')
            # login(request, user)
            return redirect('/accounts/login')
    else:
        form = SignupForm()
    return render(request,'registration/signup.html',{'form':form})



def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html',{'profile':profile})

def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method=='POST':
        userform = UserForm(request.POST,instance=request.user)
        profileform= ProfileForm(request.POST,request.FILES, instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile = profileform.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_edit.html',{'userform':userform , 'profileform':profileform})


def fav_job(request,slug):
    if request.user.is_authenticated and not request.user.is_anonymous  :
        fav = Job.objects.get(slug=slug)
        if Profile.objects.filter(user=request.user,fav_job=fav).exists():
            profile= Profile.objects.get(user=request.user)
            profile.fav_job.remove(fav)  
        else:
            profile= Profile.objects.get(user=request.user)
            profile.fav_job.add(fav)  
    else:
        return redirect('/jobs/' + slug)
    return redirect('/jobs/' + fav.slug)


def show_fav_job(request):
    context = None
    if request.user.is_authenticated and not request.user.is_anonymous:
        userInfo = Profile.objects.get(user=request.user)
        job = userInfo.fav_job.all()
        context = {'jobs':job}
    return render(request,'job/my_jobs.html',context)

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
    
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}} </span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                            </ul>
                        </div>
                        <div class="p-5boxed-btn3 w-100">
                            <a href="{% url 'accounts:profile_edit' %}" class="boxed-btn3 w-100">Edit Profile</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">

        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit Porfile</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %} 
                            {% bootstrap_form profileform %} 
                            {% buttons %}
                                 <button class="boxed-btn3 w-100" type="submit">Save</button>
                            {% endbuttons %}     
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}