PRO/urls.py
from django.contrib import admin
from django.urls import path ,include

#static import

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),

    path('jobs/', include('job.urls',namespace='jobs')),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path ,include
from . import views

app_name='job'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),                   # jobs 
    path('fav_job/<str:slug>', views.fav_job, name='fav_job'),
    path('show_fav_job', views.show_fav_job, name='show_fav_job'),
]

contact/urls.py
from django.urls import path ,include
from . import views

app_name='contact'

urlpatterns = [
    path('', views.send_message, name='contact'),  

]

job/urls.py
from django.urls import path ,include
from . import views
from . import api
from django.contrib.auth.models import User
app_name='job'

urlpatterns = [
    path('', views.job_list, name='job_list'),                   # jobs
    
    path('add',views.add_job,name= 'add_job'), # add job
    path('my_job_list',views.my_job_list,name= 'my_job_list'), 


    path('<str:slug>',views.job_detail,name='job_detail'),          # job details
    path('edit_job/<str:slug>',views.edit_job,name='edit_job'), 
    path('apply_list/<int:id>',views.apply_list,name='apply_list'), 

    ##  API

    path('api/jobs',api.job_list_api,name= 'job_list_api'),
    path('api/jobs/<int:id>',api.job_detail_api,name= 'job_detail_api'), 

    ## class 
    path('api/v2/jobs',api.JobListApi.as_view(),name= 'JobListApi'), 
    path('api/v2/jobs/create',api.JobCreate.as_view(),name= 'JobCreate'), 
    path('api/v2/jobs/<int:id>',api.JobDetail.as_view(),name= 'JobDetail'), 

]

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{%static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{%static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{%static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{%static 'css/jquery-ui.css'%}">
    <link rel="stylesheet" href="{%static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{%static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/slicknav.css'%}">

    <link rel="stylesheet" href="{%static 'css/stylee.css'%}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                       
                                        <ul id="navigation">
                                           
                                            <li><a href="{% url 'jobs:job_list' %}">Browse Job</a></li>
                                             
                                            {% comment %} <li><a href=" {% url 'contact:contact' %} "></a></li> {% endcomment %}
                                        </ul>
                                        
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                {% if request.user.is_authenticated %}
                                    <div class="col-xl-6 col-lg-7">
                                        <div class="main-menu  d-none d-lg-block">
                                            <nav>
                                                <ul id="navigation">
                                                    <li><a href="#">My Account<i class="ti-angle-down"></i></a>
                                                    <ul class="submenu">
                                                    <li><a href=" {% url 'accounts:profile' %}">My Profile </a></li>
                                                    <li><a href="{% url 'accounts:show_fav_job' %}">Favorite Jobs</a></li>
                                                    <li><a href="{% url 'jobs:my_job_list' %}">My Jobs</a></li>
                                                    <li><a href=" {% url 'logout' %} ">Log out</a></li>
                                                    </ul>
                                                    </li> 
                                                </ul>
                                            </nav>
                                        </div>
                                    </div>
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href=" {% url 'jobs:add_job' %} ">Post a Job</a>
                                    </div>
                                {% else %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a class="boxed-btn3" href=" {% url 'login' %} ">Log in</a>
                                        <a class="boxed-btn3" href=" {% url 'accounts:signup' %} ">Signup</a>
                                    </div>
                                {% endif %}    

                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block body %}
    
    {% endblock body %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="text-center">
                <p style="font-size:30px">Layal Hassan &&  Haidar Alhamoud &&  Sewar Alali && Reem Salama</p>
                </div>
            </div>
        </div>

    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
<!-- JS here -->
    <script src="{%static 'js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{%static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{%static 'js/popper.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script src="{%static 'js/owl.carousel.min.js'%}"></script>
    <script src="{%static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{%static 'js/ajax-form.js'%}"></script>
    <script src="{%static 'js/waypoints.min.js'%}"></script>
    <script src="{%static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{%static 'js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{%static 'js/scrollIt.js'%}"></script>
    <script src="{%static 'js/jquery.scrollUp.min.js'%}"></script>
    <script src="{%static 'js/wow.min.js'%}"></script>
    <script src="{%static 'js/nice-select.min.js'%}"></script>
    <script src="{%static 'js/jquery.slicknav.min.js'%}"></script>
    <script src="{%static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{%static 'js/plugins.js'%}"></script>
    <!-- <script src="{%static 'js/gijgo.min.js'%}"></script> -->
    <script src="{%static 'js/range.js'%}"></script>



    <!--contact js-->
    <script src="{%static 'js/contact.js'%}"></script>
    <script src="{%static 'js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{%static 'js/jquery.form.js'%}"></script>
    <script src="{%static 'js/jquery.validate.min.js'%}"></script>
    <script src="{%static 'js/mail-script.js'%}"></script>


    <script src="{%static 'js/main.js'%}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>     

templates/base_generic.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">

    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        {% block content %}
                        
                        {% endblock content %}

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}